### ISSUE TITLE
getting error on vendor fetch command.

### ISSUE THREAD

**Issue by flik** [avanzu/AdminThemeBundle#243] opened 2018-05-11 13:56 UTC
I am getting below error and you can check bower is also installed in windows.

php bin/console avanzu:admin:fetch-vendor
[Executing] /usr/local/bin/bower install
[Error] The system cannot find the path specified.

C:\xampp\htdocs\symfony3.4-crud-with-easyadmin-and-relations>bower

Usage:

    bower <command> [<args>] [<options>]
Commands:

    cache                   Manage bower cache
    help                    Display help information about Bower
    home                    Opens a package homepage into your favorite browser
    info                    Info of a particular package
    init                    Interactively create a bower.json file
    install                 Install a package locally
    link                    Symlink a package folder
    list                    List local packages - and possible updates
    login                   Authenticate with GitHub and store credentials
    lookup                  Look up a single package URL by name
    prune                   Removes local extraneous packages
    register                Register a package
    search                  Search for packages by name
    update                  Update a local package
    uninstall               Remove a local package
    unregister              Remove a package from the registry
    version                 Bump a package version
Options:

    -f, --force             Makes various commands more forceful
    -j, --json              Output consumable JSON
    -l, --loglevel          What level of logs to report
    -o, --offline           Do not hit the network
    -q, --quiet             Only output important information
    -s, --silent            Do not output anything, besides errors
    -V, --verbose           Makes output more verbose
    --allow-root            Allows running commands as root
    -v, --version           Output Bower version
    --no-color              Disable colors
    --config.interactive=false Disable prompts
See 'bower help <command>' for more information on a specific command.

C:\xampp\htdocs\symfony3.4-crud-with-easyadmin-and-relations>

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version : 3.4
| AdminThemeBundle  | 1.3.5/dev-master/specific-commit/tag  |
| Operating System:  Windows

**Comment by shakaran** [comment] 2019-11-23 14:55
Duplicate of #242. See the comments for the config workaround.

**Closed by shakaran** 2019-11-23 14:55 UTC
