### ISSUE TITLE
Question : How to use the form-theme only for the admin part ?

### ISSUE THREAD

**Issue by numerogeek** [avanzu/AdminThemeBundle#39] opened 2015-04-22 13:22 UTC
Hi guys,

I am using this bundle to add an admin part to my app, which have its own form theme for the front end.
This bundle provide an other form-theme, but how to use it only in the admin part ?
I'd like to avoid override my front end form theme.

**Comment by ThatCheck** [comment] 2015-04-24 08:59
You can override the default theme in twig template. So create a base.html.twig which extends all your twig template in front and use the  `{% form_theme form 'bootstrap_3_layout.html.twig' %}` in your base.html.twig

**Comment by numerogeek** [comment] 2015-04-24 09:13
Hi @ThatCheck  thx for your reply.
The point is that : 
I have specific form theme for the front (injected in the twig configuation) - and I want to use the form theme provided by avanzu only in the back end part.

For now I have used your solution : Overrided the AvanzuAdminThemeBundle:base-layout.html.twig and added 
{% if form is defined %}
    {% form_theme form 'AvanzuAdminThemeBundle:layout:form-theme.html.twig' %}
{% endif %}

(yeah, because if no form var is setted like in the dashboard, there is an error) but I am asking myself is there is no more efficient solution.

**Comment by avanzu** [comment] 2015-08-31 21:11
you should  be able to override the form  theme by referencing [mulitple templates](http://symfony.com/doc/current/cookbook/form/form_customization.html#multiple-templates) in order of priority.

**Comment by shakaran** [comment] 2017-09-28 21:37
@numerogeek the issue is resolved and replied to you or you still need more info about this? Please let me know for keep open or close it. Thanks!

**Comment by shakaran** [comment] 2017-10-22 09:39
Add some documentation about, since no reply or more comments, I gonna close this issue. Reopen if you still need some clarification, thanks!

**Closed by shakaran** 2017-10-22 09:39 UTC
Labels: 0 - Backlog, question
