### ISSUE TITLE
500 error when using the Bundle

### ISSUE THREAD

**Issue by aftabnaveed** [avanzu/AdminThemeBundle#42] opened 2015-05-16 23:26 UTC
When I try to use the bundle I get this error

Unable to find file "@AvanzuAdminThemeBundle/Resources/public/vendor/modernizr/modernizr.js" in . (which is being imported from "/vagrant/project/app/cache/dev/assetic/routing.yml").

I did try php app/console asset:install  command but seems to be not copying any folder with name vendor

**Comment by aftabnaveed** [comment] 2015-05-17 00:03
apparently the issue was with underscore.js dependency, I went into vendor/avanzu/admin-theme-bundle/Resources/bower  and executed the bower install which helps you resolve dependencies interactively.

**Comment by zghosts** [comment] 2015-09-20 13:50
Isn't this one also closed by #55/#56

**Comment by MrMitch** [comment] 2015-09-27 20:35
this is still happening with version `1.3.2`

**Comment by MrMitch** [comment] 2015-09-27 20:43
also, make sure you run `php app/console avanzu:admin:fetch-vendor` after updating ATB

**Comment by MartinLyne** [comment] 2015-10-30 16:48
According to docs bower isn't required any more, looks like fetch-vendor doesn't do anything? Using 1.3.2 and followed instructions here, I still get modernizr error. 

Is bower required again?

**Comment by shakaran** [comment] 2017-09-17 02:41
@aftabnaveed did you still have this issue in master? Some commits were pushed with fixes, please let me know if you still have the issue present or I can close the ticket

**Comment by shakaran** [comment] 2017-09-26 19:31
@MartinLyne if you are still using this bundle and you can test with master, so you can tell me if you still have the bug. I think that this is resolved. So I will automatically close in a week if I don't have notice about more user affected or reproducible

**Comment by shakaran** [comment] 2017-10-04 13:54
Since no feedback in this issue and I cannot reproduce the issue and master branch contains fixes to this. I gonna temptatively close it, but if someone finds the same behaviour or problem, don't hesitate in reopen the issue. Thanks all for the reporting!

**Closed by shakaran** 2017-10-04 13:54 UTC
Labels: 3 - Review, awaiting feedback, bug
