### ISSUE TITLE
page_title not defined

### ISSUE THREAD

**Issue by hjanuschka** [avanzu/AdminThemeBundle#150] opened 2017-02-06 09:27 UTC
hello,

after upgrading symfony to 3.2.2 and twig to: 
i get errors because "page_title" is not defined here:
https://github.com/avanzu/AdminThemeBundle/blob/4349e5edcec85404280434975670c6660c38e310/Resources/views/layout/base-layout.html.twig#L90

```
request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Block "page_title" on template "AvanzuAdminThemeBundle:layout:default-layout.html.twig" does not exist." at /opt/fxf-backend/vendor/avanzu/admin-theme-bundle/Resources/views/layout/default-layout.html.twig line 316 {"exception":"[object] (Twig_Error_Runtime(code: 0): Block \"page_title\" on template \"AvanzuAdminThemeBundle:layout:default-layout.html.twig\" does not exist. at /opt/fxf-backend/vendor/avanzu/admin-theme-bundle/Resources/views/layout/default-layout.html.twig:316)"} []
```

using feature/2.0 branch.

any ideas?

as a work around i use a empty breadcrumb block for now:

```html
{% block avanzu_breadcrumb %}
{% endblock %}
```

cc @avanzu 

regards

**Comment by shakaran** [comment] 2017-09-15 20:39
@hjanuschka probably the issue is that it is passing [as variable a block](https://twig.symfony.com/doc/2.x/tags/block.html) or calling as function which I don't know personally if it is allowed or implemented

`block('page_title')`

Probably should be rendender to pass as variable, but I don't know exactly how it should be rendered:

` {{ render(controller('AvanzuAdminThemeBundle:Breadcrumb:breadcrumb', {'request':app.request, 'title' : page_title})) }} `

**Comment by shakaran** [comment] 2017-09-18 04:06
@hjanuschka this has been fixed in master. Thanks for your report!

**Closed by shakaran** 2017-09-18 04:06 UTC
Labels: 3 - Review, bug
