### ISSUE TITLE
Error!!! Circular reference.

### ISSUE THREAD

**Issue by ernestgm2006** [avanzu/AdminThemeBundle#36] opened 2015-03-31 18:33 UTC
Hello, I created new Application Symfony and installed the bundle, but when i execute my site, show me the following error. 

FileLoaderImportCircularReferenceException in FileLoader.php line 97: Circular reference detected in "." ("." > ".").

I hope for your answers.

thank!!!

**Comment by ernestgm2006** [comment] 2015-04-01 14:47
For a better understanding of the error that is giving me the bundle will leave the following description.
After having installed the bundle using the composer.
The Active in AppKernel.php.
When I update the page then shown me the error !!!

regards

**Comment by ernestgm2006** [comment] 2015-04-01 15:41
I solved the problem by turning these lines in the file:

Avanzu\AdminThemeBundle\DependencyInjection\AvanzuAdminThemeExtension.php

/*
        if (isset($bundles['AsseticBundle'])) {

            $assets = include(dirname(__FILE__).'/../Resources/config/assets.php');

            $container->prependExtensionConfig(
                'assetic',
                array(
                    'assets'  => array(),
                    'bundles' => array(
                        'AvanzuAdminThemeBundle'
                    )

                )
            );

        }
        */

**Comment by Jawan81** [comment] 2015-04-03 13:59
As from version >=1.3 on the usage of Assetic is not required anymore (assets:install is sufficient) the bundle configuration should be extended to make the use of assetic optional. This would also avoid the unnecessary installation of node.js and bower only because other bundles have Assetic activated. So

`if (isset($bundles['AsseticBundle'])) {`

should be changed to something like

`if ($config['user_assetic'] && isset($bundles['AsseticBundle'])) {`

(though unfortunately the configuration is not directly available in the prepend method of the Extension).

**Comment by avanzu** [comment] 2015-12-29 23:40
Sorry for that. Will be fixed in 2.0.

**Comment by shakaran** [comment] 2017-09-17 02:55
@Jawan81 @ernestgm2006 since 2.0 was released time ago, I think that this should be already fixed properly. Please let me know if still reproducible for you or I could close the issue. Thanks

**Comment by shakaran** [comment] 2017-09-17 11:28
After check, this feature is now implemented in master. Please test and reopen if you see wrong behaviour again. Closing as fixed

**Closed by shakaran** 2017-09-17 11:28 UTC
Labels: 3 - Review, bug
